{ config, lib, ... }:

let
  cfg = config.fleet.service.beszel-agent-intel;
  tokenPath = "/run/secrets/beszel-agent-token";
in
{
  options.fleet.service.beszel-agent-intel = {
    publicKey = lib.mkOption {
      type = lib.types.strMatching "^ssh-ed25519 [A-Za-z0-9+/=]+( .*)?$";
      description = "Public key generated by the Beszel hub.";
    };

    tokenFile = lib.mkOption {
      type = lib.types.strMatching "^/.*";
      description = "Runtime path to the Beszel agent registration token.";
    };

    gpuDevice = lib.mkOption {
      type = lib.types.strMatching "^/dev/dri/.*";
      default = "/dev/dri/card0";
      description = "Intel GPU device exposed to the Beszel agent.";
    };
  };

  config = {
    boot.kernel.sysctl."kernel.perf_event_paranoid" = 2;

    virtualisation.oci-containers.containers.beszel-agent-intel = {
      image = "docker.io/henrygd/beszel-agent-intel:0.18.7";
      capabilities.PERFMON = true;
      devices = [ "${cfg.gpuDevice}:${cfg.gpuDevice}" ];
      environment = {
        DISABLE_SSH = "true";
        HUB_URL = "https://beszel.${config.fleet.tailscale.magicDnsSuffix}";
        KEY = cfg.publicKey;
        LISTEN = "45876";
        SYSTEM_NAME = config.networking.hostName;
        TOKEN_FILE = tokenPath;
      };
      extraOptions = [ "--network=host" ];
      volumes = [
        "/etc/localtime:/etc/localtime:ro"
        "/run/docker.sock:/var/run/docker.sock:ro"
        "beszel-agent-intel.data:/var/lib/beszel-agent"
        "${cfg.tokenFile}:${tokenPath}:ro"
      ];
    };

    systemd.services.podman-beszel-agent-intel = {
      after = [ "podman.socket" ];
      requires = [ "podman.socket" ];
      serviceConfig.Restart = lib.mkForce "always";
    };
  };
}
